# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pryaniky' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pryaniky
  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', '~> 6.1'
  pod 'FittedSheets', '~> 2.4'
end
